Repository cpr-nlp-3/moduzzi, pull requests merged in 2024-03, with the labels that each got.

#71 [BE] Course 데이터 저장 및 업데이트
  back/build.gradle
  back/src/main/java/CPR/NLP/service/CourseService.java
  back/src/main/java/CPR/NLP/service/CrawlingService.java
  back/src/main/resources/개설교과목정보.xlsx
Labels: BE, feat, fix

#74 [FE] 다크 모드의 초기 상태를 ThemeProvider에서 설정하게 수정
  front/src/context/ThemeProvider.tsx
  front/src/hooks/useTheme.ts
Labels: FE, refactor

#75 [BE] 배포 후 잘 돌아가기 위한 일부 수정
  back/src/main/java/CPR/NLP/controller/CourseController.java
  back/src/main/java/CPR/NLP/controller/ResultController.java
  back/src/main/java/CPR/NLP/service/CourseService.java
  back/src/main/java/CPR/NLP/service/CrawlingService.java
  back/src/main/java/CPR/NLP/service/PythonServiceCaller.java
Labels: BE, fix, refactor
