Repository cpr-nlp-3/moduzzi, pull requests merged in 2024-01, with the labels that each got.

#2 [OTHER] README.md 파일 작성
  README.md
Labels: docs, OTHER

#4 [FE] 프론트엔드 프로젝트 초기 세팅
  front/.eslintrc.cjs
  front/.gitignore
  front/.prettierignore
  front/.prettierrc
  front/crawler.js
  front/package-lock.json
  front/package.json
  front/tsconfig.json
  front/tsconfig.node.json
  front/vite.config.ts
  front/yarn.lock
Labels: FE, chore

#7 [BE] 백엔드 프로젝트 초기 세팅 및 entity 생성
  back/.gitignore
  back/back.md
  back/build.gradle
  back/gradle/wrapper/gradle-wrapper.jar
  back/gradle/wrapper/gradle-wrapper.properties
  back/gradlew
  back/gradlew.bat
  back/settings.gradle
  back/src/main/java/CPR/NLP/NlpApplication.java
  back/src/main/java/CPR/NLP/domain/Course.java
  back/src/main/java/CPR/NLP/domain/Result.java
  back/src/main/java/CPR/NLP/domain/Review.java
  back/src/test/java/CPR/NLP/NlpApplicationTests.java
Labels: BE, chore
