Repository cpr-nlp-3/moduzzi, pull requests merged in 2024-02, with the labels that each got.

#15 [FE] 메인 화면의 UI 및 기능 구현
  front/.eslintrc.cjs
  front/.prettierrc
  front/README.md
  front/index.html
  front/package.json
  front/public/fonts/PretendardVariable.woff2
  front/public/images/check-none.png
  front/public/images/check.png
  front/public/images/favicon.png
  front/public/images/gray-star.png
  front/public/images/logo.png
  front/public/images/search.png
  front/public/images/yellow-star.png
  front/src/App.tsx
  front/src/components/Logo/Logo.styles.tsx
  front/src/components/Logo/Logo.tsx
  front/src/main.tsx
  front/src/pages/MainPage/MainPage.styles.tsx
  front/src/pages/MainPage/MainPage.tsx
  front/src/styles/Fontstyles.styles.tsx
  front/src/styles/Globalstyles.styles.tsx
  front/src/vite-env.d.ts
  front/tsconfig.node.json
  front/yarn.lock
Labels: FE, feat, chore, design

#17 [FE] 검색 화면의 UI 및 기능 구현
  front/public/images/gray-star.png
  front/public/images/yellow-star.png
  front/src/components/List/List.styles.tsx
  front/src/components/List/List.tsx
  front/src/pages/MainPage/MainPage.styles.tsx
  front/src/pages/MainPage/MainPage.tsx
  front/src/styles/Globalstyles.styles.tsx
Labels: FE, feat, design

#22 [FE] 강의평 화면의 UI 및 기능 구현
  front/package.json
  front/public/images/gray-star.png
  front/public/images/yellow-star.png
  front/src/App.tsx
  front/src/components/Button/Button.styles.tsx
  front/src/components/Button/Button.tsx
  front/src/components/Evaluation/Details/Details.styles.tsx
  front/src/components/Evaluation/Details/Details.tsx
  front/src/components/Evaluation/Evaluation.styles.tsx
  front/src/components/Evaluation/Evaluation.tsx
  front/src/components/Evaluation/Info/Info.styles.tsx
  front/src/components/Evaluation/Info/Info.tsx
  front/src/components/Evaluation/Star/Star.styles.tsx
  front/src/components/Evaluation/Star/Star.tsx
  front/src/components/Lectures/Lectures.styles.tsx
  front/src/components/Lectures/Lectures.tsx
  front/src/components/List/List.tsx
  front/src/components/Logo/Logo.tsx
  front/src/components/Search/Search.styles.tsx
  front/src/components/Search/Search.tsx
  front/src/main.tsx
  front/src/pages/MainPage/MainPage.styles.tsx
  front/src/pages/MainPage/MainPage.tsx
  front/yarn.lock
Labels: FE, feat, refactor, design

#24 [FE] 다크모드 구현
  front/public/images/check-none.png
  front/public/images/dark-mode.png
  front/public/images/light-mode.png
  front/public/images/non-check-dark.png
  front/public/images/non-check-light.png
  front/src/App.tsx
  front/src/components/Button/Button.styles.tsx
  front/src/components/DarkMode/DarkMode.styles.tsx
  front/src/components/DarkMode/DarkMode.tsx
  front/src/components/Evaluation/Details/Details.styles.tsx
  front/src/components/Evaluation/Evaluation.tsx
  front/src/components/Evaluation/Info/Info.styles.tsx
  front/src/components/Evaluation/Star/Star.styles.tsx
  front/src/components/Lectures/Lectures.styles.tsx
  front/src/components/Search/Search.styles.tsx
  front/src/context/ThemeProvider.tsx
  front/src/hooks/useTheme.ts
  front/src/pages/MainPage/MainPage.tsx
  front/src/styles/Globalstyles.styles.tsx
  front/src/styles/Theme.ts
Labels: FE, feat, design

#26 [BE] 기본적인 조회 관련 API들과 controller, DTO 구현
  back/src/main/java/CPR/NLP/controller/CourseController.java
  back/src/main/java/CPR/NLP/controller/ResultController.java
  back/src/main/java/CPR/NLP/domain/Course.java
  back/src/main/java/CPR/NLP/domain/Result.java
  back/src/main/java/CPR/NLP/dto/CourseRequestDTO.java
  back/src/main/java/CPR/NLP/dto/CourseResponseDTO.java
  back/src/main/java/CPR/NLP/dto/ResultRequestDTO.java
  back/src/main/java/CPR/NLP/dto/ResultResponseDTO.java
  back/src/main/java/CPR/NLP/dto/ReviewRequestDTO.java
  back/src/main/java/CPR/NLP/dto/ReviewResponseDTO.java
  back/src/main/java/CPR/NLP/repository/CourseRepository.java
  back/src/main/java/CPR/NLP/repository/IntermediateRepository.java
  back/src/main/java/CPR/NLP/repository/ResultRepository.java
  back/src/main/java/CPR/NLP/repository/ReviewRepository.java
  back/src/main/java/CPR/NLP/service/CourseService.java
  back/src/main/java/CPR/NLP/service/CrawlingService.java
  back/src/main/java/CPR/NLP/service/IntermediateService.java
  back/src/main/java/CPR/NLP/service/ResultService.java
  back/src/main/java/CPR/NLP/service/ReviewService.java
Labels: BE, feat, refactor

#29 [FE] 웹 서비스 배포
  .github/workflows/deploy.yml
  front/src/context/ThemeProvider.tsx
Labels: FE, chore

#31 [FE] 별점이 제대로 보여지지 않는 오류 수정
  front/src/components/Evaluation/Details/Details.styles.tsx
  front/src/components/Evaluation/Star/Star.styles.tsx
  front/src/pages/MainPage/MainPage.tsx
Labels: FE, feat, fix, design

#33 [FE] 깃허브 액션을 이용한 자동 배포 테스트
  front/src/pages/MainPage/MainPage.tsx
Labels: FE, chore, test

#38 [FE] 모바일에서 화면이 잘려서 보이는 오류 수정
  front/src/styles/Globalstyles.styles.tsx
Labels: FE, fix

#42 [BE] 클로바 API 백엔드에 반영
  back/src/main/java/CPR/NLP/controller/CourseController.java
  back/src/main/java/CPR/NLP/controller/ResultController.java
  back/src/main/java/CPR/NLP/domain/Course.java
  back/src/main/java/CPR/NLP/domain/Intermediate.java
  back/src/main/java/CPR/NLP/domain/Result.java
  back/src/main/java/CPR/NLP/dto/CourseRequestDTO.java
  back/src/main/java/CPR/NLP/dto/CourseResponseDTO.java
  back/src/main/java/CPR/NLP/dto/ResultRequestDTO.java
  back/src/main/java/CPR/NLP/dto/ResultResponseDTO.java
  back/src/main/java/CPR/NLP/dto/ReviewRequestDTO.java
  back/src/main/java/CPR/NLP/dto/ReviewResponseDTO.java
  back/src/main/java/CPR/NLP/repository/CourseRepository.java
  back/src/main/java/CPR/NLP/repository/IntermediateRepository.java
  back/src/main/java/CPR/NLP/repository/ResultRepository.java
  back/src/main/java/CPR/NLP/repository/ReviewRepository.java
  back/src/main/java/CPR/NLP/service/CourseService.java
  back/src/main/java/CPR/NLP/service/CrawlingService.java
  back/src/main/java/CPR/NLP/service/IntermediateService.java
  back/src/main/java/CPR/NLP/service/ResultService.java
  back/src/main/java/CPR/NLP/service/ReviewService.java
Labels: BE, feat, fix

#54 [BE] 백엔드 배포가 잘 되는지 테스트
  back/requirements.txt
Labels: BE, fix, test

#55 [FE] API 연동
  front/src/components/Evaluation/Details/Details.styles.tsx
  front/src/components/Lectures/Lectures.tsx
  front/src/components/Message/Message.styles.tsx
  front/src/components/Message/Message.tsx
  front/src/pages/MainPage/MainPage.tsx
  front/vite.config.ts
Labels: FE, feat

#57 [FE] 환경변수 적용
  front/src/components/Lectures/Lectures.tsx
  front/src/pages/MainPage/MainPage.tsx
Labels: FE, feat

#59 [FE] 환경변수 오류 수정
  .github/workflows/deploy.yml
Labels: FE, fix

#61 [FE] 오류메시지 수정
  front/src/components/Lectures/Lectures.tsx
  front/src/pages/MainPage/MainPage.tsx
Labels: FE, refactor

#63 [FE] 프록시 서버 적용
  front/vite.config.ts
Labels: FE, feat

#66 [FE] 카테고리를 클릭하면 검색을 해주는 기능 구현
  front/src/components/Button/Button.tsx
  front/src/pages/MainPage/MainPage.tsx
Labels: FE, feat

#68 [FE] 강의평이 비어있어도 보여주는 오류 수정
  front/src/components/Lectures/Lectures.tsx
Labels: FE, fix

#69 [OTHER] README 업데이트
  README.md
Labels: docs, OTHER
